load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "core",
    srcs = [
        "fileio.cc",
        "geometry.cc",
        "numeric.cc",
        "polygon.cc",
    ],
   hdrs = [
       "fileio.h",
       "geometry.h",
       "numeric.h",
       "polygon.h",
       "types.h",
   ],
    deps = [],
    visibility = ["//visibility:public"],
)

